# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_AudioInfo', [dirname(__file__)])
        except ImportError:
            import _AudioInfo
            return _AudioInfo
        if fp is not None:
            try:
                _mod = imp.load_module('_AudioInfo', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _AudioInfo = swig_import_helper()
    del swig_import_helper
else:
    import _AudioInfo
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class AudioInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, AudioInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, AudioInfo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["title"] = _AudioInfo.AudioInfo_title_set
    __swig_getmethods__["title"] = _AudioInfo.AudioInfo_title_get
    if _newclass:
        title = _swig_property(_AudioInfo.AudioInfo_title_get, _AudioInfo.AudioInfo_title_set)
    __swig_setmethods__["tags"] = _AudioInfo.AudioInfo_tags_set
    __swig_getmethods__["tags"] = _AudioInfo.AudioInfo_tags_get
    if _newclass:
        tags = _swig_property(_AudioInfo.AudioInfo_tags_get, _AudioInfo.AudioInfo_tags_set)
    __swig_setmethods__["TagsSum"] = _AudioInfo.AudioInfo_TagsSum_set
    __swig_getmethods__["TagsSum"] = _AudioInfo.AudioInfo_TagsSum_get
    if _newclass:
        TagsSum = _swig_property(_AudioInfo.AudioInfo_TagsSum_get, _AudioInfo.AudioInfo_TagsSum_set)
    __swig_setmethods__["time"] = _AudioInfo.AudioInfo_time_set
    __swig_getmethods__["time"] = _AudioInfo.AudioInfo_time_get
    if _newclass:
        time = _swig_property(_AudioInfo.AudioInfo_time_get, _AudioInfo.AudioInfo_time_set)
    __swig_setmethods__["id"] = _AudioInfo.AudioInfo_id_set
    __swig_getmethods__["id"] = _AudioInfo.AudioInfo_id_get
    if _newclass:
        id = _swig_property(_AudioInfo.AudioInfo_id_get, _AudioInfo.AudioInfo_id_set)
    __swig_setmethods__["score"] = _AudioInfo.AudioInfo_score_set
    __swig_getmethods__["score"] = _AudioInfo.AudioInfo_score_get
    if _newclass:
        score = _swig_property(_AudioInfo.AudioInfo_score_get, _AudioInfo.AudioInfo_score_set)
    __swig_setmethods__["final"] = _AudioInfo.AudioInfo_final_set
    __swig_getmethods__["final"] = _AudioInfo.AudioInfo_final_get
    if _newclass:
        final = _swig_property(_AudioInfo.AudioInfo_final_get, _AudioInfo.AudioInfo_final_set)

    def __init__(self, *args):
        this = _AudioInfo.new_AudioInfo(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def __eq__(self, other):
        return _AudioInfo.AudioInfo___eq__(self, other)

    def update(self, other):
        return _AudioInfo.AudioInfo_update(self, other)
    __swig_destroy__ = _AudioInfo.delete_AudioInfo
    __del__ = lambda self: None
AudioInfo_swigregister = _AudioInfo.AudioInfo_swigregister
AudioInfo_swigregister(AudioInfo)

# This file is compatible with both classic and new-style classes.


